name: DEPLOY_RELEASE

on:
  push:
    tags:
    - 'v*-release'

jobs:
  run_tests:
    name: Run tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master   

      - name: Run tests
        run: |
          flutter pub get
          flutter test

  build_android:
    name: Build android app
    needs: run_tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - name: Build artifacts
        working-directory: android
        env:
          FLUTTER_PATH: /Users/adapps/flutter
          ANDROID_SDK_PATH: /Users/adapps/Library/Android/Sdk
          GEM_HOME: ~/.gems
        run: |
          echo "::add-path::~/.gems/bin"
          echo flutter.sdk=${{ env.FLUTTER_PATH }} > local.properties
          echo sdk.dir=${{ env.ANDROID_SDK_PATH }} >> local.properties
          echo flutter.buildMode=release >> local.properties
          echo storeFile=${{ secrets.ANDROID_KEYSTORE_PATH }} > key.properties
          echo keyAlias=${{ secrets.ANDROID_KEY_ALIAS }} >> key.properties
          echo keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }} >> key.properties
          echo storePassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }} >> key.properties
          fastlane build_android production:true
          rm -f key.properties

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: android-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload Bundle
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app.aab

  build_ios:
    name: Build iOS app
    needs: run_tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - name: Build artifacts
        working-directory: ios
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          TEMP_KEYCHAIN_NAME: ${{ secrets.TEMP_KEYCHAIN_NAME }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          GEM_HOME: ~/.gems
        run: |
          echo "::add-path::~/.gems/bin"
          fastlane build_ios

      - name: Upload IPA
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: ios-ipa
          path: ios/Runner.ipa

  deploy_android:
    name: Deploy android internal
    needs: build_android
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master   
      - name: Download AAB
        uses: actions/download-artifact@v2
        with:
          name: android-aab

      - name: Set workspace in env
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE

      - name: Deploy android
        if: success()
        working-directory: android
        env:
          AAB_PATH: ${{ env.workspace }}/app.aab
          GEM_HOME: ~/.gems
        run: |
          echo "::add-path::~/.gems/bin"
          fastlane deploy_android production:true

  deploy_ios:
    name: Deploy iOS testflight
    needs: build_ios
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master   
      - name: Download IPA
        uses: actions/download-artifact@v2
        with:
          name: ios-ipa

      - name: Set workspace in env
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE

      - name: Deploy iOS 
        if: success()
        working-directory: ios
        env:
          IPA_PATH: ${{ env.workspace }}/Runner.ipa   
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}   
          GEM_HOME: ~/.gems
        run: |
          echo "::add-path::~/.gems/bin"
          fastlane deploy_ios